name: Feature Request
description: Describe new enhancements or features that is scheduled to be done in the project.
title: "[Feature]: "
labels: [ "enhancement" ]

body:
  - type: input
    id: who
    attributes:
      label: Who
      description: Actor that performs the action that requires the feature
    validations:
      required: true

  - type: input
    id: when
    attributes:
      label: When
      description: When actor performs the action
    validations:
      required: true

  - type: input
    id: what
    attributes:
      label: What
      description: What is supposed to happen
    validations:
      required: true

  - type: textarea
    id: extra
    attributes:
      label: Extra information
      description: Any extra information that can be useful to understand the feature request
    validations:
      required: false