name: Bug Report
description: Describe any bug or issue that you find in the project, and that you think should be fixed.
title: "[Bug]: "
labels: [ "bug" ]

body:
  - type: input
    id: who
    attributes:
      label: Who
      description: Actor that performs the action that requires the feature
    validations:
      required: true

  - type: input
    id: when
    attributes:
      label: When
      description: When actor performs the action
    validations:
      required: true

  - type: input
    id: expected
    attributes:
      label: Expected
      description: What is supposed to happen
    validations:
      required: true

  - type: input
    id: actual
    attributes:
      label: Actual
      description: What is actually happening
    validations:
      required: true

  - type: textarea
    id: extra
    attributes:
      label: Extra information
      description: Any extra information that can be useful to understand the feature request
    validations:
      required: false